language: elixir

elixir: '1.10.2'
otp_release: '22.2.8'

services:
  - docker
  - postgresql

env:
  global:
    - SSH_KEY_TYPES='rsa,dsa,ecdsa'
    - DEPLOY_ARTIFACTS_PATH='deploy/artifacts'
    - DEPLOY_ROOT_DIR='/srv'
    - REPOSITORY=$(basename "$TRAVIS_REPO_SLUG")
    - BRANCH="${TRAVIS_BRANCH}"
    - BETA_BRANCH='develop'
    - DEPLOY_CHANNEL_VAR_PREFIXES="DISCORD_TOKEN,COMMAND_PREFIX"
    - ENCRYPTED_DEPLOY_KEY_PATH="deploy_key.enc"
    - ENCRYPTED_DEPLOY_KEY_CYPHER_KEY="${encrypted_dfdcfd5172af_key}"
    - ENCRYPTED_DEPLOY_KEY_IV="${encrypted_dfdcfd5172af_iv}"
    - COMMAND_PREFIX_BETA="/eb"
    - COMMAND_PREFIX_STABLE="/e"
    - HADOLINT_VERSION="1.17.5"
    - HADOLINT="${HOME}/hadolint"

install:
  - curl -sLo ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-$(uname -s)-$(uname -m)" && chmod 700 ${HADOLINT}

notifications:
  slack:
    secure: "dOj+VX6mipsA0l16v7BKvmyY0VBGaeOLk5ezLo/MiN82+/xgSWlfrTvQRZPY2O9BJnd1rX57jt4oDJzE6CAquHKzcfc5aPBreHSzJKVffMdOKYk5E0hWzd711dIhtJZUNnizaw63FEST2gM0vMRpUPSNRqt2Uo4RR/9guSizU+grDG5gES2votktKOGk2tHiTcYYqItD0DNjHmSGwjaN+rRWeavXQNxVe+YwYI9mfAjc7kQHY2dtb77KeTD50OMdM2tU/qafBu/ASi4xFlSTEnwiG7PSz2ZzKbKv2im1j1zzZ0RU8Hxi/RKApLVqb8aa8RQDBGr1DkM2+CC2gKUOcTPI5uCD4gzfRYfXIbmnQUCfhhasIaAbAK40lSmTJqgMkVhKpZnoAa6cx3yMvudzmCvg7kUhMoTLHwW0LgSsyDm6yZChszWXcOYZf0cpLIbzq/mcnxsKox8MeRNY/YvUtNIuwG3NR/Q349hEPJXkqZTJ7kCC/xlgvb90Kd3ishoWfGXB4pgI1VGXjcz5c4XXjLh4R/HWnnTlbQfoPJsYieo/Q6SVGFqfDXpJkLHBA+I5foHNVMWlXzzhtXL4Jrs4vMyZQMNNoXUiGrsQq5FEB3dXc2V9HcCpjc5hHfMMR6Tgjfle4bWa90pU4ZVs34zuVzIU4T5zuwfjMYSXdf4j7Uw="
  email: false

before_script:
  - ${HADOLINT} Dockerfile
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres

script:
  - mix local.rebar --force 
  - mix local.hex --force
  - mix deps.get
  - mix test

before_deploy:
  - eval "$(ssh-agent -s)"
  - bash "${DEPLOY_ARTIFACTS_PATH}"/setup_ssh.sh

deploy:
  - provider: script
    script: bash "${DEPLOY_ARTIFACTS_PATH}"/docker_push.sh
    skip_cleanup: true
    on:
      branch: "${BETA_BRANCH}"

  - provider: script
    script: bash "${DEPLOY_ARTIFACTS_PATH}"/docker_push.sh
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: bash "${DEPLOY_ARTIFACTS_PATH}"/deploy.sh
    skip_cleanup: true
    on:
      branch: "${BETA_BRANCH}"

  - provider: script
    script: bash "${DEPLOY_ARTIFACTS_PATH}"/deploy.sh
    skip_cleanup: true
    on:
      branch: master
