version: '3'
services:
  bot:
    build: .
    image: "jswny/edgybot:${TAG:-beta}"
    container_name: "edgybot-${TAG:-beta}"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
  db:
    image: postgres:12.2-alpine
    container_name: "edgybot-${TAG:-beta}-db"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edgybot_prod
