name: CI
on: [push]

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}
          tag_with_ref: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        uses: jswny/deploy@v2.0.0
        with:
          deploy_server: ${{ secrets.deploy_server }}
          deploy_username: ${{ secrets.deploy_username }}
          deploy_root_dir: '/srv'
          encrypted_deploy_key_encryption_key: ${{ secrets.encrypted_deploy_key_encryption_key }}
          beta_branch: 'master'
          debug: 1
          env_var_prefixes: 'DISCORD_TOKEN,COMMAND_PREFIX'
        env:
          DISCORD_TOKEN_STABLE: ${{ secrets.DISCORD_TOKEN_STABLE}}
          DISCORD_TOKEN_BETA: ${{ secrets.DISCORD_TOKEN_BETA}}
          COMMAND_PREFIX_STABLE: '/e'
          COMMAND_PREFIX_BETA: '/eb'
